domain: cinefilth.pages.dev
url: https://cinefilth.pages.dev
baseurl: ""

title: Cinefilth
email: alexander.dlx@protonmail.com
author: Alexander Delacroix

lang: en

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: pretty

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "https://cinefilth.pages.dev/email.html"
  substack: "https://alexanderdelacroix.substack.com/"
